[pytest]
markers =
    two_adults: two adults order
    four_adults: four adults order
    two_adults_two_children: two adults and two children order
    order_manipulation: to train manipulation with order
    four_adults_two_children: four adults and two children order
    two_adults_one_child: two adults and one child order